### ISSUE TITLE
Suggestion: auto scroll down message list

### ISSUE THREAD

**Issue by warpdesign** [luixaviles/socket-io-typescript-chat#11]
When a new message is received, the message list doesn't autoscroll to the bottom of the list, making the new message invisible if there is a scrollbar in `<mat-list/>`.

Suggestion: auto-scroll the message list to the bottom when a new message is received.

I had a quick look at the source code but am not sure how to do that in a clean *angular-2* way.

**Comment by ultrarunner** [comment]
I think I have a fix for this issue but I am not sure how to push it back up so that it can be merged. This would be my first attempt to fix an open issue on github. Can someone point me in the right direction? Do I have to be added as a contributor to be able to push my local branch/fix up? Thank you. Sorry.

**Comment by ultrarunner** [comment]
I figured out how to create a pull request by forking the code. Please let me know if you have any questions. Thank you.

**Comment by luixaviles** [comment]
Hi @ultrarunner. Take a look into [first-contributions](https://github.com/Roshanjossey/first-contributions) repository. You'll find the steps for your first contribution on Github.

**Comment by luixaviles** [comment]
Pull Request #12 solved this issue.
